lidar_processing_node:
  ros__parameters:
    # Lidar parameters
    num_scan_lines: 64
    scan_period: 0.1  # seconds
    vertical_angle: 2.0  # degrees
    max_dist: 90.0  # meters
    min_dist: 2.0  # meters
    # Processing parameters
    processing_frequency: 50.0  # Hz
    max_processing_queue_size: 3  # Maximum number of queued point clouds
    # QoS parameters
    queue_size: 10
    # Topic parameters
    input_topic: "kitti/velo"
    output_filtered_topic: "velodyne_points_filtered"
    output_edge_topic: "laser_cloud_edge"
    output_surf_topic: "laser_cloud_surf"

odom_estimation_node:
  ros__parameters:
    # Lidar parameters
    num_scan_lines: 64
    scan_period: 0.1  # seconds
    vertical_angle: 2.0  # degrees
    max_dist: 90.0  # meters
    min_dist: 2.0  # meters
    # Map parameters
    map_resolution: 0.4  # meters

lidar_mapping_node:
  ros__parameters:
    # Lidar parameters
    num_scan_lines: 64
    scan_period: 0.1  # seconds
    vertical_angle: 2.0  # degrees
    max_dist: 90.0  # meters
    min_dist: 2.0  # meters
    # Map parameters
    map_resolution: 0.4  # meters
